"""
DevPilot Agent State and Result Models.

Provides typed state management and structured output models for the AI Agent.
"""

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class AgentState:
    """
    Mutable state container tracked across agent reasoning iterations.
    """
    user_question: str
    messages: List[Dict[str, Any]] = field(default_factory=list)
    tool_calls: List[Dict[str, Any]] = field(default_factory=list)
    tool_results: List[Dict[str, Any]] = field(default_factory=list)
    sources: List[Dict[str, Any]] = field(default_factory=list)
    final_answer: Optional[str] = None
    iteration_count: int = 0
    stopped_reason: str = "running"

    def add_source_if_new(self, source: Dict[str, Any]) -> None:
        """Adds a source citation if not already tracked by chunk_id or file+line."""
        chunk_id = source.get("chunk_id")
        file_path = source.get("file_path")
        symbol = source.get("symbol_name")
        start_line = source.get("start_line")

        for existing in self.sources:
            if chunk_id and existing.get("chunk_id") == chunk_id:
                return
            if (
                file_path == existing.get("file_path")
                and symbol == existing.get("symbol_name")
                and start_line == existing.get("start_line")
            ):
                return

        self.sources.append(source)


@dataclass
class AgentResult:
    """
    Final structured result generated by the AI agent execution.
    """
    question: str
    answer: str
    sources: List[Dict[str, Any]] = field(default_factory=list)
    tool_calls: List[Dict[str, Any]] = field(default_factory=list)
    iterations: int = 0
    provider: str = ""
    model: str = ""
    timing: Dict[str, float] = field(default_factory=dict)
    stopped_reason: str = "completed"

    def to_dict(self) -> Dict[str, Any]:
        """Converts AgentResult to a clean JSON-serializable dictionary."""
        return {
            "question": self.question,
            "answer": self.answer,
            "sources": self.sources,
            "tool_calls": self.tool_calls,
            "iterations": self.iterations,
            "provider": self.provider,
            "model": self.model,
            "timing": {k: round(v, 4) for k, v in self.timing.items()},
            "stopped_reason": self.stopped_reason,
        }
